[package]
name = "checkpwn"
version = "0.2.7"
authors = ["brycx <brycx@protonmail.com>"]
description = "Check Have I Been Pwned and see if it's time for you to change passwords."
keywords = [ "cli", "password", "security", "HIBP" ]
categories = [ "command-line-utilities" ]
readme = "README.md"
repository = "https://github.com/brycx/checkpwn"
license = "MIT"

[dependencies]
colored = "1.7"
sha-1 = { version = "0.8.1", default-features = false }
hex = "0.3.2"
reqwest = "0.9.11"
rpassword = "2.1.0"
clear_on_drop = "0.2.3"

[dev-dependencies]
assert_cmd = "0.11.0"
